overwrite: true
schema: "./dist/schemas/"
documents: "**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript-common"
      - "typescript-client"
      - "typescript-server"
      - "typescript-resolvers"
      - "typescript-graphql-files-modules"
      - "fragment-matcher"
  ./graphql.schema.json:
    plugins:
      - "introspection"
# docs https://the-guild.dev/graphql/codegen/plugins